---
title: "Writing Functions in R"
subtitle: "Original Analysis"
output: 
  html_document:
    theme: yeti
    highlight: textmate
    toc: TRUE
    toc_float: TRUE
    df_print: paged
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
library(tidyverse)
```

## Goal
Understand county-related COVID-19 data in Delaware

## Read data

```{r}
# Link for confirmed cases
confirmed <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv"

# Link for confirmed deaths
deaths <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_US.csv"

# Read deaths
deaths_df <-
  readr::read_csv(deaths) %>%
  mutate(Type = "Deaths")

# Transform deaths
population_df <-
  deaths_df %>%
  select(UID, iso2, iso3, code3, FIPS, Admin2, Province_State, Country_Region,
         Lat, Long_, Combined_Key, Population)

# Read and transform cases
confirmed_df <- 
  readr::read_csv(confirmed) %>% 
  mutate(Type = "Confirmed") %>%
  left_join(population_df, by = c("UID", "iso2", "iso3", "code3", "FIPS",
                                  "Admin2", "Province_State", "Country_Region",
                                  "Lat", "Long_", "Combined_Key")) %>%
  select(UID, iso2, iso3, code3, FIPS, Admin2, Province_State, Country_Region,
         Lat, Long_, Combined_Key, Population, everything())

# Union cases and deaths
covid <- 
  union(confirmed_df, deaths_df) %>% 
  select(UID, iso2, iso3, code3, FIPS, Admin2, Province_State, Country_Region,
         Lat, Long_, Combined_Key, Type, Population, everything())

```

## Check County Data

```{r}
## New Castle
covid %>% 
  filter(Admin2 %in% "New Castle",
         Province_State %in% "Delaware")
```

```{r}
# Kent
covid %>% 
  filter(Admin2 %in% "Kent",
         Province_State %in% "Delaware")
```

```{r}
# Sussex
covid %>% 
  filter(Admin2 %in% "Sussex",
         Province_State %in% "Delaware")
```

```{r}
# All Delaware
covid %>% 
  filter(Province_State %in% "Delaware")
```

## Clean Data

```{r}
covid_de <- 
  covid %>% 
  
  filter(Province_State %in% "Delaware") %>% 
  
  # Turn date fields long
  pivot_longer(cols = matches("^[0-9]+\\/[0-9]+\\/[0-9]+"),
               names_to = "Date",
               values_to = "Count") %>% 
  
  # Widen based upon type
  pivot_wider(names_from = Type,
              values_from = Count) %>% 
  
  # Force Date field to be type Date
  mutate(Date = as.Date(Date, format = "%m/%d/%y")) %>% 
  
  # Move population to the end of the data frame
  select(-Population, everything(), Population)
```

## All Counties

### Confirmed Cases - Identity

```{r}
covid_de %>% 
  ggplot(aes(x = Date,
             y = Confirmed,
             color = Admin2,
             group = Admin2)) +
  geom_line() +
  scale_y_continuous(labels = scales::comma) +
  theme_minimal() +
  theme(legend.position = "top",
        axis.title = element_text(face = "bold"),
        axis.text = element_text(face = "italic")) +
  labs(color = "")
```

### Confirmed Cases - log10

```{r}
covid_de %>% 
  ggplot(aes(x = Date,
             y = Confirmed,
             color = Admin2,
             group = Admin2)) +
  geom_line() +
  scale_y_continuous(labels = scales::comma,
                     trans = "log10") +
  theme_minimal() +
  theme(legend.position = "top",
        axis.title = element_text(face = "bold"),
        axis.text = element_text(face = "italic")) +
  labs(color = "")
```

### Confirmed Deaths - Identity

```{r}
covid_de %>% 
  ggplot(aes(x = Date,
             y = Deaths,
             color = Admin2,
             group = Admin2)) +
  geom_line() +
  scale_y_continuous(labels = scales::comma) +
  theme_minimal() +
  theme(legend.position = "top",
        axis.title = element_text(face = "bold"),
        axis.text = element_text(face = "italic")) +
  labs(color = "")
```

### Confirmed Deaths - log10

```{r}
covid_de %>% 
  ggplot(aes(x = Date,
             y = Deaths,
             color = Admin2,
             group = Admin2)) +
  geom_line() +
  scale_y_continuous(labels = scales::comma,
                     trans = "log10") +
  theme_minimal() +
  theme(legend.position = "top",
        axis.title = element_text(face = "bold"),
        axis.text = element_text(face = "italic")) +
  labs(color = "")
```

